### PR TITLE
attempt to fix tags for PRs

### PR DESCRIPTION
**Pull request by blankdots**
* bump actions
* build with `sha-*` tag when pushing inside a PR
* refine check if default branch
* build when a pr was merged

this will close #7 #6 #5

### CODE REVIEW

**Comment by blankdots** [comment]
seems to fail installing openstack

**Comment by csc-felipe** [comment]
`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked`

I'll try to build locally

**Comment by csc-felipe** [comment]
It is happening locally as well.

**Comment by blankdots** [comment]
> It is happening locally as well.

well not that importat, but good to know it is broken and we might want to fix it at some point

**Comment by csc-felipe** [comment]
Yes, tried a new `RUN` command, or adding `sleep`, but it didn't work. Need to check what is keeping `sqlite` locked, or then run `postgres` instead ^^.

It's happening after creating the projects. Apparently the DB gets locked, and stays so. More investigation is needed. I'll not continue now.

**Review by csc-felipe — APPROVED** [review]

**Pull request merged**
